### ISSUE TITLE
Cuckoo28-32 won't recover solutions?

### ISSUE THREAD

**Issue by wilsonk** [xenoncat/cuckoo_pow#2]
Hello Xenoncat, I have been trying to run your cuckoo solutions here and only cuckoo20 works for me. I am running an a Ubuntu 16.04 variant (Linux Lite) on my i5-4690 with 16Gb ram. No stability issues, pretty new machine and I can run Tromps original code here without issues, but I keep getting a segv with your cuckoo programs. 

It appears as though the problem is in RecoverSolution at line https://github.com/xenoncat/cuckoo_pow/blob/4f1947c4417f4a4542c44c80a5e798e8421eefca/cuckoo28_st/cuckoo28_st.c#L1041 (...this line number changes for the other programs, of course). If I expand SIPHASH then specifically the first line ```v3 = _mm256_xor_si256(in3, nonce);``` is the one that is failing. 

Not sure what is going on, but I thought I would see if anyone else is having problems. I ran the cuckoo32 test, which used %91 of my memory and it runs fine until it tries to recover the solution also...must just be that one SIPHASH call that is misbehaving due to a bad pointer?

Any thoughts would be appreciated.
Kelly

**Comment by wilsonk** [comment]
Hello again xenoncat,

It looks like the problem I was having with your code is due to my version of gcc ```gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609```. I switched over to ```clang-3.9.1rc2``` and his code builds and runs fine. I tested Tromps code with clang and it runs ever so slightly faster than with gcc, so I assume that the timings I get with this code should be pretty comparable to gcc. At least this way I can play with things here now.

Not sure which version of gcc you were using, but at least others with gcc-5.4 could use clang instead. The only required change is to remove the -mno-vzeroupper command line arg as clang doesn't recognize that option...I also believe clang doesn't use vzeroupper by default?? Not totally sure, but I think the -x86-vzeroupper option would need to be passed for force clang to use vzeroupper.

Thanks,
Kelly

**Comment by xenoncat** [comment]
Thanks for the input. The segv issue is caused by my bad code where I try to get the compiler to output the assembly sequence that I want. It is probably some bad way of doing type casting between __m256i and uint64_t, or __builtin_assume_aligned, coupled with certain versions of gcc that cause the problem. Since this is only a proof of concept and tromp's matrix solver has successfully superseded this, I do not plan to track down this bug.

You are free to remove -mno-vzeroupper. The worst thing that can happen is just negligible performance degradation.
